/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d6c2c0",
        "surface": "#fcf9f7",
        "on-tertiary-fixed": "#002116",
        "on-surface": "#1c1c1b",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#ffdad6",
        "folder-shadow": "#A7EEF7",
         "on-error-container": "#93000a",
        "surface-container-high": "#eae8e6",
        "white-paper": "#FFFFFF",
        "surface-dim": "#dcd9d8",
        "folder-cyan": "#91dcee",
        "on-primary-container": "#fcdad6",
        "tertiary": "#002c1f",
        "on-secondary-fixed-variant": "#5c403a",
        "surface-container-low": "#f6f3f1",
        "outline": "#847371",
        "tertiary-container": "#114333",
        "surface-bright": "#fcf9f7",
        "primary-fixed-dim": "#f9b6af",
        "error-container": "#ffdad6",
        "surface-variant": "#e5e2e0",
        "on-surface-variant": "#3f3231",
        "on-primary-fixed": "#34100d",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3f0ee",
        "on-secondary-fixed": "#2b1611",
        "accent-sand": "#D6B48C",
        "tertiary-fixed-dim": "#9fd1bb",
        "on-primary-fixed-variant": "#693935",
        "on-tertiary-fixed-variant": "#1f4f3e",
        "inverse-surface": "#31302f",
        "surface-container-highest": "#e5e2e0",
        "secondary-container": "#ffd7ce",
        "on-secondary": "#ffffff",
        "primary-container": "#5b2e2a",
        "primary": "#411916",
        "background": "#fcf9f7",
        "secondary-fixed-dim": "#e5beb5",
        "tertiary-fixed": "#bbeed7",
        "surface-tint": "#85504b",
        "secondary": "#513a36",
        "on-background": "#1c1c1b",
        "on-primary": "#ffffff",
        "surface-container": "#f0edeb",
        "inverse-primary": "#f9b6af",
        "on-secondary-container": "#513a36",
        "secondary-fixed": "#ffdad3",
        "on-tertiary-container": "#7fb09b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "workspace-margin": "40px",
        "object-gap": "32px"
      },
      fontFamily: {
        "display-xl-mobile": ["Instrument Serif", "serif"],
        "display-xl": ["Instrument Serif", "serif"],
        "headline-md": ["Instrument Serif", "serif"],
        "headline-lg": ["Instrument Serif", "serif"],
        "caption": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "display-xl-mobile": ["64px", { "lineHeight": "60px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-xl": ["120px", { "lineHeight": "110px", "letterSpacing": "-0.04em", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "36px", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "52px", "fontWeight": "400" }],
        "caption": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
